name: 问题反馈
description: 当你在代码中发现了一个Bug，导致网站崩溃或无法正常显示运行，或者有一个组件存在问题，或者某些地方看起来不对劲。
title: "[问题反馈] 请在此输入标题"
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        感谢对项目的支持与关注。我们将积极修复任何反馈的问题！
  - type: checkboxes
    attributes:
      label: 这个问题是否未被提出？
      options:
        - label: 我确保我已经搜索过现有的问题 (https://github.com/REmcbbs/REmcbbs/issues)
          required: true
  - type: input
    attributes:
      label: 设备信息 - 系统及版本
      description: 请告诉我们您访问REmcbbs的设备系统名称及版本。
    validations:
      required: true
  - type: input
    attributes:
      label: 设备信息 - 浏览器及版本
      description: 请告诉我们您访问REmcbbs的浏览器名称及版本。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 如何复现
      description: 请详细告诉我们如何复现你遇到的问题。
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期结果
      description: 请告诉我们你预期会发生什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际结果
      description: 请告诉我们实际发生了什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图或视频（可选）
      description: 如果可以的话，上传任何关于问题的截图。
      value: |
        [在这里上传图片]
    validations:
      required: false
